version: '3.3'
services:
 build-agent:
  container_name: build-agent
  image: build-agent:build
  build:
   context: .
   dockerfile: Dockerfile.build
 test-agent:
  container_name: test-agent
  image: test-agent:test
  build:
   context: .
   dockerfile: Dockerfile.test
  depends_on:
  - build-agent
