version: '3.3'
services:
 build-agent:
  container_name: build-agent
  image: docker-build:build
  build:
   context: .
   dockerfile: Dockerfile-build
 test-agent:
  container_name: test-agent
  image: test:test
  build:
   context: .
   dockerfile: Dockerfile-test
  depends_on:
  - build-agent
