version: '3.3'
services:
 build-agent:
  container_name: build-agent-wire
  image: wire
  build:
   context: .
   dockerfile: Dockerfile-build
 test-agent:
  container_name: test-agent-wire
  image: test:latest
  build:
   context: .
   dockerfile: Dockerfile-test
  depends_on:
  - build-agent
